In [2]:
import pandas as pd
import numpy as np


# 배열 만들기
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
print(np.array([3, 1.4, 2, 3, 4.5]))
# numpy array는 단일 데이터 타입만 저장 가능
# 정수와 실수가 혼용 시 더 큰 범위인 실수로 자동 변경

[3.  1.4 2.  3.  4.5]


In [6]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [10]:
print(np.array([1,2,3,4]))
print(np.array([1,2,3,4], dtype = float))
# 'dtype=' 로 데이터 타입 지정 가능

print()
arr = np.array([1,2,3,4], dtype = float)
print(arr)
print(arr.dtype)
print(arr.astype(int)) # 원본은 변경 안됨
print(arr) # 원본은 변경 안됨

[1 2 3 4]
[1. 2. 3. 4.]

[1. 2. 3. 4.]
float64
[1 2 3 4]
[1. 2. 3. 4.]


In [11]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# start, end, step
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# start, end, 요소 개수
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# 난수 활용
np.random.random((2,2))
# 0~1 사이 균일 분포 난수 생성
# (2,2) : size(튜플 형식) >> 매개 변수로 받아서 난수 생성

array([[0.96563599, 0.43952393],
       [0.34032097, 0.50817114]])

In [21]:
np.random.rand(2,2)
# 0~1 사이 균일 분포 난수 생성
# 직접 차원(2,2) 인수 넣어줌

array([[0.05913027, 0.11002471],
       [0.10245961, 0.97506559]])

In [25]:
# (평균, 표준편차, 구조)
np.random.normal(0, 1, (2,2))
# 정규분포를 만드는데 구조 매개변수를 (2,2) 튜플로 받아서 난수 생성

array([[ 0.5656336 ,  0.77257489],
       [-0.34624933, -2.14452463]])

In [26]:
np.random.randn(2,2)
# rand인데 정규 분포를 따르는 값으로 생성
# 평균 0 표준편차 1을 입력 안해줘도 default 값으로 지정되어 있음

array([[ 1.26744612,  0.20222846],
       [-4.04364808, -0.36695351]])

In [30]:
np.random.randint(0, 10, (2,2))
# 0이상 10미만의 정수 범위에서 (2,2) 구조의 배열을 만든다

array([[7, 2],
       [2, 1]])

In [33]:
# 배열의 기초

np.random.randint(10, size = (3,4))

array([[4, 2, 5, 9],
       [3, 8, 9, 8],
       [9, 6, 8, 9]])

In [35]:
x = np.random.randint(10, size = (3,4))

print(x.ndim) # 차원
print(x.shape) # 형태 (n,m)
print(x.size) # 크기(원소의 개수)
print(x.dtype) # 데이터 타입

2
(3, 4)
12
int32


In [36]:
# indexing과 slicing

np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [38]:
# indexing
a = np.arange(7)

print(a[3])
print(a[-3])

a[0] = 10
print(a)

3
4
[10  1  2  3  4  5  6]


In [46]:
# slicing

print(a)
print()
print(a[1:4]) # 1이상 4미만
print(a[1:]) # 1번째 부터 끝까지
print(a[::2]) # 전체를 2의 인터벌로 추출
print(a[::-1]) # 역순
print(a[-3::-1]) # 역순으로 추출하는데 역순에서 -3번째부터 끝까지

[10  1  2  3  4  5  6]

[1 2 3]
[1 2 3 4 5 6]
[10  2  4  6]
[ 6  5  4  3  2  1 10]
[ 4  3  2  1 10]


In [51]:
# reshape (형태 변경) (중요)

x = np.arange(8)
print(x)
print()
print(x.shape)
print()

x2 = x.reshape((2,4))
print(x2) # 2차원 (2,4) 행렬로 변환
print(x2.shape)

[0 1 2 3 4 5 6 7]

(8,)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [55]:
# concatenate(이어 붙이기)

x1 = np.array([0, 1, 2])
x2 = np.array([3, 4, 5])

print(x1)
print(x2)
print(np.concatenate([x1,x2]))

[0 1 2]
[3 4 5]
[0 1 2 3 4 5]


In [58]:
# concatenate(이어 붙이기) axis 축 기준 이어 붙이기

m = np. arange(4).reshape(2,2)

print(m)
print()
print(np.concatenate([m,m]))
print()
print(np.concatenate([m,m], axis=0))
# axis=0 (default, 설정된 기본값)
# 열을 기준으로 세로로 이어 붙임(행세)
print()
print(np.concatenate([m,m], axis=1))
# axis=1 (축 기준 바꿈)
# 행을 기준으로 가로로 이어 붙임(열가)
print()


[[0 1]
 [2 3]]

[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1 0 1]
 [2 3 2 3]]



In [62]:
# split(나누기)
np.arange(16).reshape(4,4)

m = np.arange(16).reshape(4,4)

print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [64]:
print(np.split(m, [3], axis=0))
# 자를 배열, 기준, 기준 축
# m을 3의 열을 기준으로 나눠줘

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [66]:
# 자른 배열 할당해서 출력하기
m1, m2 = np.split(m, [3], axis=0)

print(m1)
print()
print(m2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [65]:
print(np.split(m, [3], axis=1))
# 자를 배열, 기준, 기준 축
# m을 3의 행을 기준으로 나눠줘

[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [67]:
# 자른 배열 할당해서 출력하기
m3, m4 = np.split(m, [3], axis=1)

print(m3)
print()
print(m4)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

[[ 3]
 [ 7]
 [11]
 [15]]


넘파이 연산

In [73]:
# array의 모든 원소에 5를 더하는 함수 생성

def add_5(v):
    output = np.empty(len(v))
    
    for i in range(len(v)):
        output[i] = v[i] + 5
    return output

v = np.random.randint(1,10,(5))

print(v)
print(add_5(v))

[4 3 3 3 6]
[ 9.  8.  8.  8. 11.]


In [78]:
# loop vs numpy

big_arr = np.random.randint(1,10,(10000000))

print(add_5(big_arr))

[13. 10.  9. ...  9.  8.  6.]


In [80]:
# 브로드 캐스팅 되어 계산
# loop 보다 빠르고 함수 만들 필요 없음
print(big_arr + 5)

[13 10  9 ...  9  8  6]


In [69]:
# 5개의 원소를 가진 1차원 배열 생성
# 초기화는 되어 있지 않음 >> 배열의 메모리 공간은 할당되었지만 그 안의 값은 랜덤이거나 기본값으로 설정되지 않았다
# 여기에 출력되는 값은 메모리에 이미 존재한 임의의 값으로 배열 채움
np.empty(5)

array([0.00000000e+000, 1.11408641e-311, 1.11408641e-311, 1.11408641e-311,
       0.00000000e+000])

In [81]:
# 기본 연산

np.arange(4)

array([0, 1, 2, 3])

In [82]:
x = np.arange(4)

print(x+5)
print(x-5)
print(x*5)
print(x/5)

[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]


In [83]:
# 행렬 간 연산

x = np.arange(4).reshape((2,2))

y = np.random.randint(0,10,(2,2))

print(x+y)
print(x-y)
print(x*y)
print(x/y)


[[ 6  2]
 [11 10]]
[[-6  0]
 [-7 -4]]
[[ 0  1]
 [18 21]]
[[0.         1.        ]
 [0.22222222 0.42857143]]


In [86]:
# 브로드 캐스팅 (BroadCasting) : 행렬의 모양이 달라도 행 또는 열 중 하나만 수가 같으면 연산 가능

print(x)
print()
print(x+5) # (2,2)배열 x에 5라는 스칼라 값을 더할 수 있는게 브로드 캐스팅 때문이다.

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


In [93]:
# 집계 함수

x = np.arange(8).reshape((2,-1))

print(x)
print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))


[[0 1 2 3]
 [4 5 6 7]]
28
0
7
3.5


In [95]:
# axis 사용, 집계하기

x = np.arange(8).reshape((2,-1))

print(x)
print()
print(np.sum(x, axis=0))
# 행을 기준으로 세로로 더함
# 1열의 1행, 2행을 더한 값 : 4
# 2열의 1행, 2행을 더한 값 : 6
# 3열의 1행, 2행을 더한 값 : 8
# 4열의 1행, 2행을 더한 값 : 10
# 결과값 [4 6 8 10]
print()
print(np.sum(x, axis=1))
# 열을 기준으로 가로로 더함
# 1행의 1열, 2열, 3열, 4열을 더한 값 : 6
# 2행의 1열, 2열, 3열, 4열을 더한 값 : 22
# 결과값 [6 22]

[[0 1 2 3]
 [4 5 6 7]]

[ 4  6  8 10]

[ 6 22]


In [100]:
x = np.arange(5)

print(x<3)
print()
print(x>3)

# 활용
print('활용')
print(x[x<3]) # x의 요소 중 3 보다 작은 값을 출력해줘

# 실무 활용
print('실무 활용')
condition = x < 3
print(x[condition])

[ True  True  True False False]

[False False False False  True]
활용
[0 1 2]
실무 활용
[0 1 2]
