### 라이브러리(Library)
- 특정 기능을 수행하는 코드의 모음
- 자주 사용되는 기능 코드를 모아서 라이브러리로 만들어 놓고 재사용하므로 개발 시간을 절약하고 코드의 품질을 높일 수 있다
- 종류
    - 표준 라이브러리
        - > 파이썬에서 기본적으로 내장되어 제공하는 라이브러리로 별도의 설치가 필요없이 바로 사용가능 (math, datetime, os, sys, re 등등)
    - 외부 라이브러리(서드 파티 라이브러리)
        - > 파이썬에 내장되어 있지 않지만 제 3자가 개발하여 배포하는 라이브러리로 별도의 설치를 통해 사용가능 (numpy, pandas, matplotlib, scikit-learn 등등)
    - 커스텀 라이브러리
        - > 사용자가 특정 용도에 맞게 작성한 라이브러리
        - 특정 프로젝트나 기능을 위해 맞춤 제작
        - 유지 보수 작성자가 직접해야함

### import

In [1]:
# 어떤 라이브러리든 파이썬에 불러오려면 import를 사용해야 한다

import math
print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [4]:
# math 모듈
# 모듈(module) : 모듈은 다른 사람이 정의한 변수의 모음
# 내장함수 dir()을 사용하여 해당 모듈의 모든 이름을 볼 수 있다

print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [5]:
# 우리는 '.' 을 사용하여 다음과 같은 변수에 접근할 수 있다
# math.pi >> '.'을 사용해 모듈의 'pi' 변수에 접근함
# 'pi' 변수는 원주율을 나타내는 변수로 끝없이 소수점이 이어지기 때문에 포매팅 {:.4}로 소수점 3번째 자리까지 나오게 했다

print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [6]:
# 변수외에도 모듈에 들어있는 함수에도 접근할 수 있다

# math 모듈에 내장된 log()함수에 접근
math.log(32, 2)

5.0

In [7]:
# 생소한 모듈의 함수가 어떤식으로 기능하는지 알고자 하면 help()를 사용하면 된다
help(math.log)

# log(x, [base=math.e])
# 뒤에 수를 밑으로 가지는 로그에 앞의 수를 진수로 가지는 값을 호출하는 함수


Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [8]:
# help(math) 처럼 모듈에 대한 전체 설명을 한번에 볼 수도 있다 (호출값 길어서 생략)

### 다른 import 구문

as

In [9]:
# 가져오는 모듈 또는 라이브러리 이름을 짧은 별명으로 나타낼 수 있게 해준다
# 라이브러리의 이름이 너무 길면 매번 코드 작성 시 불편하므로 알아볼 수 있는 짧은 별명으로 지칭하기 위해 사용한다

import math as mt
mt.pi

3.141592653589793

In [10]:
# as 사용 예시
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
# '*' : 모듈에 있는 변수에 직접 접근할 수 있게 해주는 구문
from math import *

# 원래라면 math.pi, math.log() 이렇게 모듈명 뒤에 접근자 '.'를 사용하여 접근해야했는데
# '*' 를 import 하므로 모듈 이름 없이 변수명, 함수명 만드로 직접 접근가능하게 된다
print(pi, log(32,2))

3.141592653589793 5.0


In [13]:
# 그러나 '*' 는 모호함을 가져올 수 있다
# 예시
from math import *
from numpy import *

print(pi, log(32, 2))
# TypeError: return arrays must be of ArrayType
# 에러 발생
# log()가 math에도 있지만 같은 이름의 log()가 numpy에도 존재
# 따라서 후에 쓰인 numpy의 log()가 호출되었는데 numpy의 log() 함수는 기능이 math의 log()와 달라서 인수가 맞지 않아 에러가 발생

# 즉, * 는 실제 코드에서 거의 쓰이지 않는다

TypeError: return arrays must be of ArrayType

In [15]:
# 이러한 문제점을 적절히 해결하기 위해 각 모듈에서 필요한 특정 항목만 가져온다

from math import pi, log
from numpy import asarray

print(pi, log(32, 2))
# math의 log()만 불러왔기 때문에 출동없이 잘 출력된다

3.141592653589793 5.0


### 서브 모듈(submodules)

In [16]:
# 모듈은 다른 모듈을 참조하는 변수를 가질 수 있다

import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

# 위와 같이 numpy 모듈에서 '.'을 사용하여 random 이라는 모듈을 가져올 수 있다
# 즉, 모듈은 변수, 함수 외에도 모듈을 내장할 수 있다 (모듈 안에 모듈 = 서브 모듈)

numpy.random is a <class 'module'>
it contains names such as... ['set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [18]:
# 모듈의 서브모듈을 불러와서도 추가로 변수나 함수 호출도 얼마든지 가능하다

# Roll 10 dice
rolls = numpy.random.randint(low=1, high=6, size=10) # 최소가 1 최대가 6인(마치 주사위) 숫자 중 사이즈(길이)가 10이 되도록 랜덤하게 값을 뽑아라
rolls

array([3, 1, 5, 1, 2, 2, 1, 2, 5, 5])

### 파이썬에서 생소한 것을 이해하기 위한 3가지 유용한 도구

type()

In [19]:
# 이게 뭔가요? (이건 어떤 타입인가요?)
type(rolls)

numpy.ndarray

dir()

In [20]:
# 이걸로 뭘 할 수 있나요? (이것에 어떤 것을 적용할 수 있나요? - 함수 등등)
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [21]:
# dir(rolls) 결과에 mean이 존재한다 -> mean() 사용가능
rolls.mean()

2.7

In [22]:
# dir(rolls) 결과에 tolist가 존재한다 -> tolist() 사용가능
rolls.tolist()

[3, 1, 5, 1, 2, 2, 1, 2, 5, 5]

help()

In [23]:
# 하나씩 더 자세히 알려주세요
# dir(rolls) 결과에 ravel이 존재는 하는데 ravel이 어떻게 적용되는 거지?

help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



### 연산자 오버로딩(Operator overloading)

- 연산자 오버로딩 : 사용자 정의 객체(모듈, 라이브러리 등등)에 대해 기존의 파이썬 연산자(+,-,*,/ 등등)의 동작을 재정의할 수 있게 해주는 기능
- 예시) 파이썬 기존 환경에서 리스트(배열의 일종)와 수치형 데이터의 계산이 불가능하지만 numpy 모듈에서는 배열(array)과 수치형 데이터의 연산이 가능하다

In [24]:
# 에러 발생
# 파이썬의 경우 리스트와 수치형 데이터의 연산이 불가능

[3, 4, 1, 2, 2, 1] + 10

TypeError: can only concatenate list (not "int") to list

In [25]:
# 그러나 numpy를 사용한 array 데이터는 가능하다
# +10이 각 배열의 요소에 각각 적용되어 나타난다

rolls + 10

array([13, 11, 15, 11, 12, 12, 11, 12, 15, 15])

즉, 위의 예시로 알 수 있는 연산자 오버로딩의 예시는 다음과 같다
- numpy 환경에서 파이썬 연산자 '+'의 기능이 재정의됨 >> 각각 더해줄 수 있게 재정의

In [26]:
# 비교 연산자도 가능
rolls <= 3

array([ True,  True, False,  True,  True,  True,  True,  True, False,
       False])

In [34]:
# 이중 리스트
xlist = [[1,2,3],[2,4,6],]

# numpy를 사용하여 이중 리스트(xlist)를 2차원의 배열 형태로 바꿔줄 수 있다
# 차이점 xlist는 단순히 리스트 안에 리스트들이 ','로 연결되어 있다(행과 열의 개념 존재x)면 2차원 배열은 ',' 없이 행렬의 형태로 존재한다
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [35]:
# numpy array의 2번째 열에 마지막 요소
x[1,-1]

6

In [36]:
# 이건 오류가 발생한다 >> 리스트에 들어가는 인덱스는 정수나 슬라이싱 기호(:) 여야하는데
# 1,-1과 같은 튜플 형태가 들어갔으니 에러 발생
xlist[1,-1]

TypeError: list indices must be integers or slices, not tuple

1+1이 2가 되지 않는 경우

In [40]:
# %pip install tensorflow

In [39]:
import tensorflow as tf
# Create two constants, each with value 1
a = tf.constant(1)
b = tf.constant(1)
# Add them together to get...
a + b

# a+b가 2가 아니라 tensorflow에서 사용하는 값이 2인 텐서가 생성된다
# 즉, 단순히 수를 더하는 것처럼 보여도 각기 다른 모듈 환경에서는 전혀 다른 예측 값이 나올 수 있다

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [43]:
# help() 또는 dir() 을 사용하면 나오는 결과물에서 '__add__'와 같이 변수 이름 양옆에 두개의 밑줄
# 연산자 오버로딩과 직접적으로 관련이 있다

# 연산자가 사용자 정의 객체에서 어떻게 동작하는지 정의하고 싶을때 사용

# 예시
x = 2

print(x in [1,2,3])
print([1, 2, 3].__contains__(x))
# __contains__는 연산자 in과 정확히 똑같이 동작한다
# 즉, in 연산자의 동작을 정의한 것이 __contains__ 이다

True
True
